version: "3"

services:
  timezone-service:
        image: "yuricampolongo/timezone-tokyo-service"
        expose:
            - "3000"
        ports:
            - 3000:3000
        restart: on-failure   
  timezone-portal:
        image: "yuricampolongo/timezone-tokyo-portal"
        expose:
            - "4200"
        links:
            - timezone-service
        depends_on: 
            - timezone-service
        ports:
            - 4200:4200
        restart: on-failure   