FROM golang:1.16
# Set the Current Working Directory inside the container
WORKDIR $GOPATH/src/github.com/yuricampolongo/timezone-tokyo-exercise/services
# Copy everything from the current directory to the PWD (Present Working Directory) inside the container
COPY ./services/ ./
# Download all the dependencies
RUN go get -d -v ./...
# Install the package
RUN go install -v ./timezones/...
# Expose port 3000
EXPOSE 3000
# Run the executable
CMD ["timezones"]